name: Continuous integration

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
    - main
  schedule:
  - cron: "0 0 * * FRI"


jobs:
  test:
    name: check_update_test
    runs-on: restreamio/gstreamer:x86_64-latest-dev-with-source
    steps:
    - uses: actions/checkout@v2
    - name: Install gstreamer dev
      run: apt update && apt install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: check
    - uses: actions-rs/cargo@v1
      with:
        command: update
    - uses: actions-rs/cargo@v1
      with:
        command: test
